# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NHDZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Kingfisher'
    pod 'SwiftLint'
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'SVProgressHUD'
    pod 'BMPlayer'
    pod 'FMDB'
    pod 'ObjectMapper'
  # Pods for NHDZ

end
